Use 'xmllint' instead of 'grep'

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -18,26 +18,29 @@ jobs:
           server-id: ossrh
           server-username: MAVEN_USERNAME
           server-password: MAVEN_PASSWORD
+      - name: Install xmllint
+        run: |
+          sudo apt-get update -q
+          sudo apt-get install -y libxml2-utils
       - name: Verify Version from pom.xml
         run: |
-            # Extract the version from pom.xml using grep
-            POM_VERSION=$(grep -oP '<version>\K[^<]+' pom.xml)
-            
-            # Get the release tag from the GitHub context
-            RELEASE_TAG=${{ github.ref }}
-            
-            # Remove "refs/tags/" from the release tag
-            RELEASE_TAG=${RELEASE_TAG/refs\/tags\//}
+          # Extract the version from pom.xml using grep
+          POM_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
+  
+          # Get the release tag from the GitHub context
+          RELEASE_TAG=${{ github.ref }}
           
-            # Remove the 'v' prefix from the release tag, if present
-            RELEASE_TAG=${RELEASE_TAG#v}
-            
-            if [ "$POM_VERSION" == "$RELEASE_TAG" ]; then
-              echo "Version in pom.xml matches the release tag: $RELEASE_TAG"
-            else
-              echo "Error: Version in pom.xml ($POM_VERSION) does not match the release tag ($RELEASE_TAG)"
-              exit 1
-            fi
+          # Remove "refs/tags/" from the release tag
+          RELEASE_TAG=${RELEASE_TAG/refs\/tags\//}
+        
+            # Remove the 'v' prefix fro the release tag, if present
+            RELEASE_TAG=${RELEASE_TAG#v}            
+          if [ "$POM_VERSION" == "$RELEASE_TAG" ]; then
+            echo "Version in pom.xml matches the release tag: $RELEASE_TAG"
+          else
+            echo "Error: Version in pom.xml ($POM_VERSION) does not match the release tag ($RELEASE_TAG)"
+            exit 1
+          fi
       - name: Publish to the Maven Central Repository
         run: mvn --batch-mode -Dmaven.test.skip deploy
         env:
